version: "3.8"

services:
  mysql:
    image: "mysql:latest"
    volumes:
      - "./obo.sql:/docker-entrypoint-initdb.d/init.sql"
      - "mysql_data:/var/lib/mysql"
    env_file:
      - .env

  obo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8080"
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql_data:
